# Generated by Django 4.0 on 2023-04-24 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellregistrations.communitygroup')),
            ],
        ),
        migrations.CreateModel(
            name='MembersDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('whatsapp_number', models.CharField(default='', max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='male', max_length=1)),
                ('age', models.CharField(choices=[('18-25', '18-25'), ('26-34', '26-34'), ('35-39', '35-39'), ('40-49', '40-49'), ('50 and above', '50 and above')], default='', max_length=15)),
                ('marital_status', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=50)),
                ('is_member', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='yes', max_length=1)),
                ('center', models.CharField(blank=True, max_length=50)),
                ('church', models.CharField(blank=True, max_length=50)),
                ('hear', models.CharField(blank=True, max_length=50)),
                ('is_first', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='yes', max_length=1)),
                ('consent', models.BooleanField(default='')),
                ('sub_community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellregistrations.subcommunity')),
            ],
        ),
    ]
