# Generated by Django 4.0 on 2023-04-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellregistrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersdetail',
            name='whatsapp_number',
            field=models.CharField(default='+234', max_length=15),
        ),
    ]
